CREATE TABLE IF NOT EXISTS public.request_logs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NULL,
    CONSTRAINT request_logs_pkey PRIMARY KEY (id),
    CONSTRAINT request_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;
